apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
    name: ingress-srv
    annotation: 
        kubernetes.io/ingress.class: ngix
        ngix.ingress.kubernetes.io/use-regex: 'true'
spec:
    rules: 
          # Dont forget to add path in this route c:/windows/system32/drivers/etc/hosts 
          # 127.0.0.1 pranser.com (nameof host)
        - host: pranser.com
          http: 
            paths: 
                - path: /api/platforms
                  pathType: Prefix
                  backend:
                    service: 
                        name: platforms-clusterip-service
                        port: 
                            number: 80
                - path: /api/c/platforms
                  pathType: Prefix
                  backend:
                    service:
                        name: commands-clusterip-srv
                        port:
                            number:80
        
  